apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-service
  namespace: dpp-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration-service
  template:
    metadata:
      labels:
        app: collaboration-service
    spec:
      containers:
        - name: collaboration-service
          image: dpp/collaboration-service:latest
          ports:
            - containerPort: 8000
