version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/services/simulation-engine"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/services/compliance-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/services/gamification-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/services/edc-simulator"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/services/collaboration-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/services/platform-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/services/platform-core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/services/aas-adapter"
    schedule:
      interval: "weekly"
