apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: dpp-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: dpp/api-gateway:latest
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /kong/declarative/kong.yml
            - name: KEYCLOAK_URL
              value: "http://keycloak"
            - name: KEYCLOAK_REALM
              value: "dpp"
            - name: KONG_ALLOW_ANONYMOUS
              value: "false"
            - name: KONG_CORS_ORIGINS
              value: "https://dpp.local"
          ports:
            - containerPort: 8000
