apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: dpp-playground
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: kong
        static_configs:
          - targets: ["kong:8000"]
      - job_name: simulation-engine
        metrics_path: /metrics
        static_configs:
          - targets: ["simulation-engine:80"]
      - job_name: compliance-service
        metrics_path: /metrics
        static_configs:
          - targets: ["compliance-service:80"]
      - job_name: gamification-service
        metrics_path: /metrics
        static_configs:
          - targets: ["gamification-service:80"]
      - job_name: edc-simulator
        metrics_path: /metrics
        static_configs:
          - targets: ["edc-simulator:80"]
      - job_name: collaboration-service
        metrics_path: /metrics
        static_configs:
          - targets: ["collaboration-service:80"]
